% This function defines the data-collection task for pivotal HTT study

% collect "Evaluable/Not Evaluable" for sTILs in each ROI
% IF ROI is "Evaluable" collect % Tumor Associated Stroma & sTILs Density

% task input column
% HTT_TILS_Pivotal_20x,TaskID,TaskOrder,Slot,ROI_X,ROI_Y,ROI_W,ROI_H,Qtext


% task output column
% HTT_TILS_Pivotal_20x,TaskID,TaskOrder,Slot,ROI_X,ROI_Y,ROI_W,ROI_H,Qtext,
% duration,status,percentstroma,score

function task_HTT_TILS_pivotal_20x(hObj)
    try

        % Initialize handles, myData, taskinfo, and calling_function
        handles = guidata(hObj);
        myData = handles.myData;
        taskinfo = myData.taskinfo;
        calling_function = handles.myData.taskinfo.calling_function;

        display([taskinfo.task, ' called from ', calling_function])

        % Manage the GUI based on the calling_function
        switch calling_function

            case 'Load_Input_File'

                % Initialize GUI, handles, taskinfo, desc
                taskinfo_default(hObj, taskinfo)
                handles = guidata(hObj);
                taskinfo = handles.myData.taskinfo;
                taskinfo.rotateback = 0;
                taskinfo.showingROI = 1;

                % Downsample the task image by 1/2
                taskinfo.img_w = taskinfo.roi_w / 2;
                taskinfo.img_h = taskinfo.roi_h / 2;

                % Check if there is output data
                if length(taskinfo.desc)>9
                    myData.finshedTask = myData.finshedTask + 1;
                end

            case {'Update_GUI_Elements', ...
                    'ResumeButtonPressed'} % Initialize task elements

                % Load the image
                ROIname = [handles.myData.task_images_dir, taskinfo.id, '.tif'];
                taskinfo.ROIname = ROIname;
                taskinfo.showingROI = 1;
                handles.myData.taskinfo = taskinfo;
                guidata(hObj, handles);
                taskimage_load(hObj);
                handles = guidata(hObj);

                % Show management buttons
                taskmgt_default(handles, 'on');
                handles = guidata(hObj);

                % Initialize UI objects for question 1, visible
                initializeQ1(hObj)

                % Initialize UI objects for question 2, not visible
                initializeQ2(hObj)

                % Initialize UI objects for question 3, not visible
                initializeQ3(hObj)

                % switch ROI
                handles.switchROI = uicontrol(...
                    'Parent', handles.task_panel, ...
                    'FontSize', handles.myData.settings.FontSize, ...
                    'Units', 'normalized', ...
                    'ForegroundColor',  handles.myData.settings.FG_color, ...
                    'BackgroundColor',  handles.myData.settings.BG_color, ...
                    'Position',[0.85,0.85,0.15,0.15], ...
                    'Style', 'pushbutton', ...
                    'Tag', 'editvalue', ...
                    'Enable','on',...
                    'visible','on',...
                    'String', 'Switch to WSI thumbnail',...
                    'Callback',@switchROI_Callback);

            case {'NextButtonPressed', ...
                    'PauseButtonPressed',...
                    'Backbutton_Callback',...
                    'Refine_Register_Button_Callback'} % Clean up the task elements

                % Hide image and management buttons
                taskmgt_default(handles, 'off');
                handles = guidata(hObj);
                set(handles.iH,'visible','off');
                set(handles.ImageAxes,'visible','off');

                % Find all uicontrols created above
                %     Tags 'Q1', 'Q2', 'Q3', 'switchROI'
                objectsToRemove = [
                    findobj(handles.task_panel, 'Tag', 'Q1');
                    findobj(handles.task_panel, 'Tag', 'Q2');
                    findobj(handles.task_panel, 'Tag', 'Q3');
                    findobj(handles.task_panel, 'Tag', 'switchROI');
                    ];

                % Initialize a list to store field names to remove
                fieldsToRemove = {};

                % Iterate over the fields of the handles structure
                fieldNames = fieldnames(handles);
                for i = 1:length(fieldNames)
                    field = fieldNames{i};
                    % Check if the field's value is in the list of objects to remove
                    if ismember(handles.(field), objectsToRemove)
                        % Add field name to the list
                        fieldsToRemove{end+1} = field;
                    end
                end

                % Remove the fields from handles
                for i = 1:length(fieldsToRemove)
                    handles = rmfield(handles, fieldsToRemove{i});
                end

                % Delete Q1 objects from GUI and from handles
                for i = 1:length(objectsToRemove)
                    delete(objectsToRemove(i));
                end



                % Delete Q1 objects from GUI and from handles
                tagQ1 = findobj(handles.task_panel, 'Tag', 'Q1');
                for i = 1:length(tagQ1)
                    delete(tagQ1(i));
                    handles = rmfield(handles, tag);
                end

                % Delete Q2 objects
                tagQ2 = findobj(handles.task_panel, 'Tag', 'Q2');
                for i = 1:length(tagQ2); delete(tagQ2(i)); end

                % Delete Q3 objects
                tagQ3 = findobj(handles.task_panel, 'Tag', 'Q3');
                for i = 1:length(tagQ3); delete(tagQ3(i)); end

                % Delete switchROI object
                delete(handles.switchROI);


                handles = rmfield(handles, 'question2text');
                handles = rmfield(handles, 'question1panel');
                handles = rmfield(handles, 'radiobutton1A');
                handles = rmfield(handles, 'radiobutton1B');
                handles = rmfield(handles, 'radiobutton1C');
                handles = rmfield(handles, 'radiobutton1D');

                handles = rmfield(handles, 'question1text');
                handles = rmfield(handles, 'question2panel');
                handles = rmfield(handles, 'radiobutton2T');
                handles = rmfield(handles, 'radiobutton2F');

                handles = rmfield(handles, 'question3text');
                handles = rmfield(handles, 'slider');
                handles = rmfield(handles, 'editvalue');
                handles = rmfield(handles, 'textleft');
                handles = rmfield(handles, 'textcenter');
                handles = rmfield(handles, 'textright');
                handles = rmfield(handles, 'textscore');

                handles = rmfield(handles, 'switchROI');

                taskimage_archive(handles);

            case 'exportOutput' % export current task information and reuslt

                % If 1, write task output
                if taskinfo.currentWorking == 1
                    fprintf(myData.fid, [...
                        taskinfo.task, ',', ...
                        taskinfo.id, ',', ...
                        num2str(taskinfo.order), ',', ...
                        num2str(taskinfo.slot), ',',...
                        num2str(taskinfo.roi_x), ',',...
                        num2str(taskinfo.roi_y), ',', ...
                        num2str(taskinfo.roi_w), ',', ...
                        num2str(taskinfo.roi_h), ',', ...
                        taskinfo.text, ',', ...
                        num2str(taskinfo.duration), ',', ...
                        num2str(taskinfo.question1result), ',', ...
                        taskinfo.question2result, ',', ...
                        taskinfo.question3result]);

                    % If 0, write incomplete task
                elseif taskinfo.currentWorking == 0
                    fprintf(myData.fid, [...
                        taskinfo.task, ',', ...
                        taskinfo.id, ',', ...
                        num2str(taskinfo.order), ',', ...
                        num2str(taskinfo.slot), ',',...
                        num2str(taskinfo.roi_x), ',',...
                        num2str(taskinfo.roi_y), ',', ...
                        num2str(taskinfo.roi_w), ',', ...
                        num2str(taskinfo.roi_h), ',', ...
                        taskinfo.text]);

                    % write tasks completed from previous session
                else
                    desc = taskinfo.desc;
                    for i = 1 : length(desc)-1
                        fprintf(myData.fid,[desc{i},',']);
                    end
                    fprintf(myData.fid,[desc{length(desc)}]);
                end

                % End the file with a carraige return and newline
                fprintf(myData.fid,'\r\n');

                % Pack up the data
                handles.myData.taskinfo = taskinfo;
                guidata(handles.GUI, handles);

        end

        % Update handles.myData.taskinfo and pack
        myData.taskinfo = taskinfo;
        handles.myData = myData;
        guidata(hObj, handles);

    catch ME
        error_show(ME)
    end
end

function initializeQ1(hObj)

    % Initialize handles
    handles = guidata(hObj);

    % Initialize text for Q1
    handles.question1text = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', [0.1,0.75,0.1,0.1], ...
        'Style', 'text', ...
        'Tag', 'Q1', ...
        'String', 'ROI Type:');

    % Initialize tissue type button group
    handles.question1panel = uibuttongroup( ...
        'Parent',handles.task_panel,...
        'Position',[0.2,0.75,0.4,0.1],...
        'SelectionChangedFcn',@radiobutton1_Callback, ...
        'Tag', 'Q1');

    % Intialize radio button 1, Evaluable
    handles.radiobutton1A = uicontrol(...
        'Parent', handles.question1panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', [0,0,0.5,1], ...
        'Style', 'radiobutton', ...
        'Tag', 'Q1', ...
        'String', 'Evaluable for sTILs');

    % Intialize radio button 2, Not Evaluable
    handles.radiobutton1B = uicontrol(...
        'Parent', handles.question1panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', [0.5,0,0.5,1], ...
        'Style', 'radiobutton', ...
        'Tag', 'Q1', ...
        'String', 'Not Evaluable for sTILs');

    % Deselect all radio buttons
    set(handles.question1panel, 'SelectedObject', []);

end

function initializeQ2(hObj)

    % Initialize handles
    handles = guidata(hObj);

    % Initialize text for Q2
    handles.textQ2 = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', [.1, .6, .8, .1], ...
        'Style', 'text', ...
        'Visible','off',...
        'Tag', 'Q2', ...
        'String', 'What is % Tumor-Associated Stroma?');

    % Initialize the slider position, size, and init value
    initvalue = -1;
    slider_x = .1;
    slider_y = .4;
    slider_w = .55;
    slider_h = .1;
    position = [slider_x, slider_y, slider_w, slider_h];

    % Initialize slider not visible
    handles.sliderStroma = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', [.95, .95, .95], ...
        'Position', position, ...
        'Style', 'slider', ...
        'Tag','textQ2', ...
        'String', 'slider_string', ...
        'Min', -1, ...
        'Max', 100, ...
        'SliderStep', [1.0/101.0, 10.0/101.0], ...
        'Value', initvalue, ...
        'Visible','off', ...
        'Tag','Q2', ...
        'Callback', @sliderStroma_Callback);

    % Initialize text label at 0
    position = [slider_x, slider_y+slider_h, .1, .1];
    handles.textStroma000 = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', position, ...
        'Style', 'text', ...
        'Visible','off', ...
        'Tag','Q2', ...
        'String', '0');

    % Initialize text label at 50
    position = [slider_x+slider_w/2-.05, slider_y+slider_h, .1, .1];
    handles.textStroma050 = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', position, ...
        'Style', 'text', ...
        'Visible','off', ...
        'Tag','Q2', ...
        'String', '50');

    % Initialize text label at 100
    position = [slider_x+slider_w-.1, slider_y+slider_h, .1, .1];
    handles.textStroma100 = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', position, ...
        'Style', 'text', ...
        'Visible','off', ...
        'Tag','Q2', ...
        'String', '100');

    % Initialize input box for number that is "linked" to slider
    position = [slider_x+slider_w+.05, slider_y, .1, slider_h];
    handles.editStroma = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', [.95, .95, .95], ...
        'Position', position, ...
        'Style', 'edit', ...
        'Visible','off',...
        'Tag','Q2', ...
        'String', num2str(initvalue), ...
        'Callback', @editvalue_Callback);

    % Initialize text for numeric input box
    position = [slider_x+slider_w+.05, slider_y+slider_h, .1, .1];
    handles.textEditStroma = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', position, ...
        'Style', 'text', ...
        'Visible','off', ...
        'Tag','Q2', ...
        'String', '%');

    % Save handles
    guidata(hObj, handles);

end

function initializeQ3(hObj)

    % Initialize handles
    handles = guidata(hObj);

    % Initialize text for Q3
    handles.textQ3 = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', [.1, .25, .8, .1], ...
        'Style', 'text', ...
        'Visible','off',...
        'Tag','Q3', ...
        'String', 'What is % Tumor-Associated Stroma?');

    % Initialize the slider position, size, and init value
    initvalue = -1;
    slider_x = .1;
    slider_y = .05;
    slider_w = .55;
    slider_h = .1;
    position = [slider_x, slider_y, slider_w, slider_h];

    % Initialize slider not Visible
    handles.sliderTILs = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', [.95, .95, .95], ...
        'Position', position, ...
        'Style', 'slider', ...
        'Tag', 'Q3', ...
        'String', 'slider_string', ...
        'Min', -1, ...
        'Max', 100, ...
        'SliderStep', [1.0/101.0, 10.0/101.0], ...
        'Value', initvalue, ...
        'Visible','off',...
        'Callback', @sliderTILs_Callback);

    % Initialize text label at 0
    position = [slider_x, slider_y+slider_h, .1, .1];
    handles.textTILs0000 = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', position, ...
        'Style', 'text', ...
        'Visible','off', ...
        'Tag','Q3', ...
        'String', '0');

    % Initialize text label at 50
    position = [slider_x+slider_w/2-.05, slider_y+slider_h, .1, .1];
    handles.textTILs050 = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', position, ...
        'Style', 'text', ...
        'Visible','off', ...
        'Tag','Q3', ...
        'String', '50');

    % Initialize text label at 100
    position = [slider_x+slider_w-.1, slider_y+slider_h, .1, .1];
    handles.textTILs100 = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', position, ...
        'Style', 'text', ...
        'Visible','off',...
        'Tag','Q3', ...
        'String', '100');

    % Initialize input box for number that is "linked" to slider
    position = [slider_x+slider_w+.05, slider_y, .1, slider_h];
    handles.editTILs = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', [.95, .95, .95], ...
        'Position', position, ...
        'Style', 'edit', ...
        'Value', initvalue, ...
        'Visible','off', ...
        'Tag', 'Q3', ...
        'String', num2str(initvalue), ...
        'Callback', @valueTILs_Callback);

    % Initialize text for numeric input box
    position = [slider_x+slider_w+.05, slider_y+slider_h, .1, .1];
    handles.textEditTILs = uicontrol(...
        'Parent', handles.task_panel, ...
        'FontSize', handles.myData.settings.FontSize, ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'center', ...
        'ForegroundColor', handles.myData.settings.FG_color, ...
        'BackgroundColor', handles.myData.settings.BG_color, ...
        'Position', position, ...
        'Style', 'text', ...
        'Visible','off', ...
        'Tag','Q3', ...
        'String', '%');

    % Save handles
    guidata(hObj, handles);

end

function closeObjects(hObj, objectsToRemove)

    % Initialize handles
    handles = guidata(hObj);

    % Initialize a list to store field names to remove
    fieldsToRemove = {};

    % Iterate over the fields of the handles structure
    fieldNames = fieldnames(handles);
    for i = 1:length(fieldNames)
        field = fieldNames{i};

        % Skip the field if it is not a UI control
        if(~isa(handles.(field), 'matlab.ui.control.UIControl'))
            continue
        end

        % Check if the field's value is in the list of objects to remove
        if ismember(handles.(field), objectsToRemove)
            % Add field name to the list
            fieldsToRemove{end+1} = field;
        end
    end

    % Remove the fields from handles
    for i = 1:length(fieldsToRemove)
        handles = rmfield(handles, fieldsToRemove{i});
    end

    % Delete Q1 objects from GUI and from handles
    for i = 1:length(objectsToRemove)
        delete(objectsToRemove(i));
    end

    % Save handles
    guidata(hObj, handles);

end

function radiobutton1_Callback(hObj, eventdata)
    try

        % Initialize handles
        handles = guidata(hObj);

        % Find and close all objects from Q2 and Q3 objects
        objectsToRemove =[
            findobj(handles.task_panel, 'Tag', 'Q2');
            findobj(handles.task_panel, 'Tag', 'Q3');
            ];
        closeObjects(hObj, objectsToRemove)

        % Initialize Q2 and Q3
        initializeQ2(hObj)
        initializeQ3(hObj)

        % Initialize handles and taskinfo
        % handles = guidata(findobj('Tag','GUI'));
        handles = guidata(hObj);
        taskinfo = handles.myData.tasks_out{handles.myData.iter};

        % Get the result for the selected button
        % 'Evaluable for sTILs' or 'Not Evaluable for sTILs'
        taskinfo.question1result = get(eventdata.NewValue, 'String');

        % Change the ui based on the selected button
        if strcmp(taskinfo.question1result, 'Evaluable for sTILs')

            % If Evaluable, make Q2 objects visible
            tagQ2 = findobj(handles.task_panel, 'Tag', 'Q2');
            for i = 1:length(tagQ2); tagQ2(i).Visible = 'on'; end

        else

            % Set output data
            taskinfo.question2result = 'NA';
            taskinfo.question3result = 'NA';

            % Not Evaluable, enable next button
            set(handles.NextButton,'Enable','on');

            % Give  focus to the next button
            uicontrol(handles.NextButton);

        end

        % Pack the results
        handles.myData.tasks_out{handles.myData.iter} = taskinfo;
        guidata(handles.GUI, handles);

    catch ME
        error_show(ME)
    end

end

function radiobutton2_Callback(hObj, eventdata)
    try

        handles = guidata(findobj('Tag','GUI'));
        taskinfo = handles.myData.tasks_out{handles.myData.iter};

        taskinfo.button_desc = get(eventdata.NewValue, 'Tag');
        switch taskinfo.button_desc
            case 'radiobutton2T'
                taskinfo.question2result = 'T';
            case 'radiobutton2F'
                taskinfo.question2result = 'F';
        end

        % Change the ui based on the  button
        if strcmp(taskinfo.question2result, 'T')
            set(handles.question3text,'Enable','on');
            set(handles.slider,'Enable','on');
            set(handles.textleft,'Enable','on');
            set(handles.textcenter,'Enable','on');
            set(handles.textright,'Enable','on');
            set(handles.editvalue,'Enable','on');
            set(handles.textscore,'Enable','on');
            set(handles.NextButton,'Enable','off');
        else
            set(handles.NextButton,'Enable','on');
            set(handles.question3text,'Enable','off');
            set(handles.slider,'Enable','off');
            set(handles.textleft,'Enable','off');
            set(handles.textcenter,'Enable','off');
            set(handles.textright,'Enable','off');
            set(handles.editvalue,'Enable','off');
            set(handles.textscore,'Enable','off');
            taskinfo.question3result = 'NA';
            uicontrol(handles.NextButton);
        end


        % Pack the results
        handles.myData.tasks_out{handles.myData.iter} = taskinfo;
        guidata(handles.GUI, handles);

    catch ME
        error_show(ME)
    end

end




function slider_Callback(hObj, eventdata)
    try

        handles = guidata(findobj('Tag','GUI'));
        taskinfo = handles.myData.tasks_out{handles.myData.iter};

        set(handles.slider, 'BackgroundColor', [.95, .95, .95]);

        score = round(get(hObj, 'Value'));
        set(handles.editvalue, 'String', num2str(score));
        set(handles.NextButton, 'Enable', 'on');
        uicontrol(handles.NextButton);

        taskinfo.question3result = num2str(score);
        handles.myData.tasks_out{handles.myData.iter} = taskinfo;
        guidata(handles.GUI, handles);

    catch ME
        error_show(ME)
    end

end


function editvalue_Callback(hObj, eventdata)
    handles = guidata(findobj('Tag','GUI'));
    taskinfo = handles.myData.tasks_out{handles.myData.iter};

    score = str2double(get(handles.editvalue, 'String'));

    if score > 100
        score = 100;
        set(handles.editvalue, 'String', '100');
        set(handles.slider, 'Value', 100);
    elseif score < 0
        score = 0;
        set(handles.editvalue, 'String', '0');
        set(handles.slider, 'Value', 0);
    end

    set(handles.slider, ...
        'BackgroundColor', [.95, .95, .95], ...
        'Value', score);
    set(handles.NextButton,'Enable','on');
    uicontrol(handles.NextButton);

    % Pack the results
    taskinfo.question3result = num2str(score);
    handles.myData.tasks_out{handles.myData.iter} = taskinfo;
    guidata(handles.GUI, handles);

end

function switchROI_Callback(hObj, eventdata) %#ok<DEFNU>
    handles = guidata(hObj);
    myData = handles.myData;
    taskinfo = handles.myData.tasks_out{handles.myData.iter};
    if taskinfo.showingROI == 0
        ROIname = [handles.myData.task_images_dir, taskinfo.id, '.tif'];
        taskinfo.ROIname = ROIname;
        taskinfo.showingROI = 1;
        set(handles.switchROI,'String','Switch to WSI thumbnail');
        myData.taskinfo = taskinfo;
        myData.tasks_out{myData.iter} = taskinfo;
        handles.myData = myData;
        guidata(hObj, handles);
        taskimage_load(hObj);
    else
        wsi_info = myData.wsi_files{taskinfo.slot};
        WSIfile=wsi_info.fullname;
        slideIndex = strfind(WSIfile,'\');
        fileName = WSIfile((slideIndex(end)+1): end);
        dotIndex = strfind(fileName,'.');
        fileName = fileName(1: (dotIndex(end)-1));
        ROIname = [handles.myData.task_images_dir, fileName, '_thumb.tif'];
        taskinfo.ROIname = ROIname;
        taskinfo.showingROI = 0;
        set(handles.switchROI,'String','Switch to ROI');

        if ~isfile(ROIname)
            roi_w = max(wsi_info.wsi_w);
            roi_h = max(wsi_info.wsi_h);
            roi_x = floor(roi_w/2+1);
            roi_y = floor(roi_h/2+1);
            Left = 1;
            Top  = 1;
            mp = get(0, 'MonitorPositions');
            screensize= mp(find(mp(:,1)==1&mp(:,2)==1),:);
            if  roi_w/ roi_h>(screensize(4)*0.8)/screensize(3);
                img_w = floor(screensize(4)*0.7)/2;
                img_h = 0;
            else
                img_w = 0;
                img_h = floor(screensize(3)*0.9)/2;
            end
            WSIfile=wsi_info.fullname;
            success = ExtractROI_BIO(wsi_info, WSIfile, ROIname,...
                Left, Top, roi_w, roi_h,...
                img_w, img_h,...
                handles.myData.settings.RotateWSI,...
                wsi_info.rgb_lut);
        end
        myData.taskinfo = taskinfo;
        myData.tasks_out{myData.iter} = taskinfo;
        handles.myData = myData;
        guidata(hObj, handles);
        taskimage_load(hObj);
    end

    handles = guidata(hObj);

end
