function task_checkMof4(hObj)
%description
%choose M of out 4 check box

%task input column
%checkMof4,TaskID,TaskOrder,Slot,ROI_X,ROI_Y,ROI_W,ROI_H,Qtext,Q_Op1,Q_Op2,Q_Op3,Q_Op4

%task output column
%checkMof4,TaskID,TaskOrder,Slot,ROI_X,ROI_Y,ROI_W,ROI_H,Qtext,Q_Op1,Q_Op2,Q_Op3,Q_Op4,
%task duration,Q1_result,Q2_result,Q3_result,Q4_result
try
    
    handles = guidata(hObj);
    myData = handles.myData;
    taskinfo = myData.taskinfo;
    calling_function = handles.myData.taskinfo.calling_function;
    
    display([taskinfo.task, ' called from ', calling_function])
    
    switch calling_function
        
        case 'Load_Input_File' % Read in the taskinfo
            
            taskinfo_default(hObj, taskinfo)
            handles = guidata(hObj);
            taskinfo = handles.myData.taskinfo;
            desc = taskinfo.desc;  
            taskinfo.q_op1 = char(desc{10});
            taskinfo.q_op2 = char(desc{11});
            taskinfo.q_op3 = char(desc{12});
            taskinfo.q_op4 = char(desc{13});
            taskinfo.rotateback = 0;
            taskinfo.checkboxresult=zeros(1,4);
            if length(taskinfo.desc)>13
                myData.finshedTask = myData.finshedTask + 1;
            end
        case {'Update_GUI_Elements', ...
                'ResumeButtonPressed'} % Initialize task elements

            % Load the image
            taskimage_load(hObj);
            handles = guidata(hObj);

            % Show management buttons
            taskmgt_default(handles, 'on');
            handles = guidata(hObj);
            
            
            
                        % checkbox
            handles.checkbox1 = uicontrol(...
                'Parent', handles.task_panel, ...
                'FontSize', handles.myData.settings.FontSize, ...
                'Units', 'Characters', ...
                'HorizontalAlignment', 'left', ...
                'ForegroundColor', handles.myData.settings.FG_color, ...
                'BackgroundColor', handles.myData.settings.BG_color, ...
                'Position', [10,6,25,2], ...
                'Style', 'checkbox', ...
                'Callback',@checkbox1_Callback, ...
                'String', taskinfo.q_op1);
            
           handles.checkbox2 = uicontrol(...
                'Parent', handles.task_panel, ...
                'FontSize', handles.myData.settings.FontSize, ...
                'Units', 'Characters', ...
                'HorizontalAlignment', 'left', ...
                'ForegroundColor', handles.myData.settings.FG_color, ...
                'BackgroundColor', handles.myData.settings.BG_color, ...
                'Position', [35,6,25,2], ...
                'Style', 'checkbox', ...
                'Callback',@checkbox2_Callback, ...
                'String', taskinfo.q_op2);
          
            handles.checkbox3 = uicontrol(...
                'Parent', handles.task_panel, ...
                'FontSize', handles.myData.settings.FontSize, ...
                'Units', 'Characters', ...
                'HorizontalAlignment', 'left', ...
                'ForegroundColor', handles.myData.settings.FG_color, ...
                'BackgroundColor', handles.myData.settings.BG_color, ...
                'Position', [60,6,25,2], ...
                'Style', 'checkbox', ...
                'Callback',@checkbox3_Callback, ...
                'String', taskinfo.q_op3);
            
            handles.checkbox4 = uicontrol(...
                'Parent', handles.task_panel, ...
                'FontSize', handles.myData.settings.FontSize, ...
                'Units', 'Characters', ...
                'HorizontalAlignment', 'left', ...
                'ForegroundColor', handles.myData.settings.FG_color, ...
                'BackgroundColor', handles.myData.settings.BG_color, ...
                'Position', [85,6,25,2], ...
                'Style', 'checkbox', ...
                'Callback',@checkbox4_Callback, ...
                'String', taskinfo.q_op4);
      
            
% old code            
            
%             set(handles.checkbox1,'FontSize', myData.settings.FontSize,...
%                 'BackgroundColor',myData.settings.BG_color,...
%                 'ForegroundColor',myData.settings.FG_color);
%             set(handles.checkbox2,'FontSize', myData.settings.FontSize,...
%                 'BackgroundColor',myData.settings.BG_color,...
%                 'ForegroundColor',myData.settings.FG_color);
%             set(handles.checkbox3,'FontSize', myData.settings.FontSize,...
%                 'BackgroundColor',myData.settings.BG_color,...
%                 'ForegroundColor',myData.settings.FG_color);
%             set(handles.checkbox4,'FontSize', myData.settings.FontSize,...
%                 'BackgroundColor',myData.settings.BG_color,...
%                 'ForegroundColor',myData.settings.FG_color);
% 
%             handles.radiobutton1 = uicontrol(...
%                 'Parent', handles.task_panel, ...
%                 'FontSize', handles.myData.settings.FontSize, ...
%                 'Units', 'Characters', ...
%                 'HorizontalAlignment', 'left', ...
%                 'ForegroundColor', handles.myData.settings.FG_color, ...
%                 'BackgroundColor', handles.myData.settings.BG_color, ...
%                 'Position', [10,6,25,2], ...
%                 'Style', 'radiobutton', ...
%                 'Tag', 'radiobutton1', ...
%                 'String', taskinfo.q_op1);
%             
%             handles.radiobutton2 = uicontrol(...
%                 'Parent', handles.task_panel, ...
%                 'FontSize', handles.myData.settings.FontSize, ...
%                 'Units', 'Characters', ...
%                 'HorizontalAlignment', 'left', ...
%                 'ForegroundColor', handles.myData.settings.FG_color, ...
%                 'BackgroundColor', handles.myData.settings.BG_color, ...
%                 'Position', [35,6,25,2], ...
%                 'Style', 'radiobutton', ...
%                 'Tag', 'radiobutton2', ...
%                 'String', taskinfo.q_op2);
% 
%             handles.radiobutton3 = uicontrol(...
%                 'Parent', handles.task_panel, ...
%                 'FontSize', handles.myData.settings.FontSize, ...
%                 'Units', 'Characters', ...
%                 'HorizontalAlignment', 'left', ...
%                 'ForegroundColor', handles.myData.settings.FG_color, ...
%                 'BackgroundColor', handles.myData.settings.BG_color, ...
%                 'Position', [60,6,25,2], ...
%                 'Style', 'radiobutton', ...
%                 'Tag', 'radiobutton3', ...
%                 'String', taskinfo.q_op3);
% 
%             handles.radiobutton4 = uicontrol(...
%                 'Parent', handles.task_panel, ...
%                 'FontSize', handles.myData.settings.FontSize, ...
%                 'Units', 'Characters', ...
%                 'HorizontalAlignment', 'left', ...
%                 'ForegroundColor', handles.myData.settings.FG_color, ...
%                 'BackgroundColor', handles.myData.settings.BG_color, ...
%                 'Position', [85,6,25,2], ...
%                 'Style', 'radiobutton', ...
%                 'Tag', 'radiobutton4', ...
%                 'String', taskinfo.q_op4);
%             
%             set(handles.task_panel, ...
%                 'SelectionChangeFcn', @radiobutton_Callback, ...
%                 'SelectedObject', []);
            
        case {'NextButtonPressed', ...
                'PauseButtonPressed',...
                'Backbutton_Callback',...
                'Refine_Register_Button_Callback'} % Clean up the task elements

            % Hide image and management buttons
            taskmgt_default(handles, 'off');
            handles = guidata(hObj);
            

            set(handles.iH,'visible','off');
            set(handles.ImageAxes,'visible','off');
            delete(handles.checkbox1);
            delete(handles.checkbox2);
            delete(handles.checkbox3);
            delete(handles.checkbox4);
            handles = rmfield(handles, 'checkbox1');
            handles = rmfield(handles, 'checkbox2');
            handles = rmfield(handles, 'checkbox3');
            handles = rmfield(handles, 'checkbox4');
            %old
%             delete(handles.radiobutton1);
%             delete(handles.radiobutton2);
%             delete(handles.radiobutton3);
%             delete(handles.radiobutton4);
%             handles = rmfield(handles, 'radiobutton1');
%             handles = rmfield(handles, 'radiobutton1');
%             handles = rmfield(handles, 'radiobutton1');
%             handles = rmfield(handles, 'radiobutton1');
%             
            taskimage_archive(handles);
        case 'exportOutput' % export current task information and reuslt
            if taskinfo.currentWorking ==1 % write finish task in current study
                fprintf(myData.fid, [...
                    taskinfo.task, ',', ...
                    taskinfo.id, ',', ...
                    num2str(taskinfo.order), ',', ...
                    num2str(taskinfo.slot), ',',...
                    num2str(taskinfo.roi_x), ',',...
                    num2str(taskinfo.roi_y), ',', ...
                    num2str(taskinfo.roi_w), ',', ...
                    num2str(taskinfo.roi_h), ',', ...
                    taskinfo.text, ',', ...
                    taskinfo.q_op1, ',', ...
                    taskinfo.q_op2, ',', ...
                    taskinfo.q_op3, ',', ...
                    taskinfo.q_op4, ',', ...
                    num2str(taskinfo.duration), ',', ...
                    num2str(taskinfo.checkboxresult(1)),',',...
                    num2str(taskinfo.checkboxresult(2)),',',...
                    num2str(taskinfo.checkboxresult(3)),',',...
                    num2str(taskinfo.checkboxresult(4))]);
          elseif taskinfo.currentWorking ==0 % write undone task
                fprintf(myData.fid, [...
                    taskinfo.task, ',', ...
                    taskinfo.id, ',', ...
                    num2str(taskinfo.order), ',', ...
                    num2str(taskinfo.slot), ',',...
                    num2str(taskinfo.roi_x), ',',...
                    num2str(taskinfo.roi_y), ',', ...
                    num2str(taskinfo.roi_w), ',', ...
                    num2str(taskinfo.roi_h), ',', ...
                    taskinfo.text, ',', ...
                    taskinfo.q_op1, ',', ...
                    taskinfo.q_op2, ',', ...
                    taskinfo.q_op3, ',', ...
                    taskinfo.q_op4]);
            else                               % write done task from previous study
                desc = taskinfo.desc;
                for i = 1 : length(desc)-1
                    fprintf(myData.fid,[desc{i},',']);
                end
                fprintf(myData.fid,[desc{length(desc)}]);
            end            
            fprintf(myData.fid,'\r\n');
            handles.myData.taskinfo = taskinfo;
            guidata(handles.GUI, handles);               
%         case 'Save_Results' % Save the results for this task
%             
%             fprintf(taskinfo.fid, [...
%                 taskinfo.task, ',', ...
%                 taskinfo.id, ',', ...
%                 num2str(taskinfo.order), ',', ...
%                 num2str(taskinfo.slot), ',',...
%                 num2str(taskinfo.roi_x), ',',...
%                 num2str(taskinfo.roi_y), ',', ...
%                 num2str(taskinfo.roi_w), ',', ...
%                 num2str(taskinfo.roi_h), ',', ...
%                 num2str(taskinfo.img_w), ',', ...
%                 num2str(taskinfo.img_h), ',', ...
%                 taskinfo.text, ',', ...
%                 num2str(taskinfo.moveflag), ',', ...
%                 num2str(taskinfo.zoomflag), ',', ...
%                 taskinfo.q_op1, ',', ...
%                 taskinfo.q_op2, ',', ...
%                 taskinfo.q_op3, ',', ...
%                 taskinfo.q_op4, ',', ...
%                 num2str(taskinfo.duration), ',', ...
%                 num2str(taskinfo.buttonID), ',', ...
%                 taskinfo.button_desc]);
%             fprintf(taskinfo.fid,'\r\n');
            
    end

    % Update handles.myData.taskinfo and pack
    myData.taskinfo = taskinfo;
    handles.myData = myData;
    guidata(hObj, handles);

catch ME
    error_show(ME)
end
end

function checkbox1_Callback(hObj, eventdata)
try
    
    handles = guidata(findobj('Tag','GUI'));
    taskinfo = handles.myData.tasks_out{handles.myData.iter};
    if (get(hObj,'Value') == get(hObj,'Max'))
        taskinfo.checkboxresult(1)=1;
    else
        taskinfo.checkboxresult(1)=0;
    end
    set(handles.NextButton,'Enable','on');
    % Pack the results
    handles.myData.tasks_out{handles.myData.iter} = taskinfo;
    guidata(handles.GUI, handles);

catch ME
    error_show(ME)
end
end

function checkbox2_Callback(hObj, eventdata)
try
    
    handles = guidata(findobj('Tag','GUI'));
    taskinfo = handles.myData.tasks_out{handles.myData.iter};
    if (get(hObj,'Value') == get(hObj,'Max'))
        taskinfo.checkboxresult(2)=1;
    else
        taskinfo.checkboxresult(2)=0;
    end
    set(handles.NextButton,'Enable','on');
    % Pack the results    
    handles.myData.tasks_out{handles.myData.iter} = taskinfo;
    guidata(handles.GUI, handles);

catch ME
    error_show(ME)
end
end

function checkbox3_Callback(hObj, eventdata)
try
    
    handles = guidata(findobj('Tag','GUI'));
    taskinfo = handles.myData.tasks_out{handles.myData.iter};

    if (get(hObj,'Value') == get(hObj,'Max'))
        taskinfo.checkboxresult(3)=1;
    else
        taskinfo.checkboxresult(3)=0;
    end
    set(handles.NextButton,'Enable','on');
    % Pack the results

    handles.myData.tasks_out{handles.myData.iter} = taskinfo;
    guidata(handles.GUI, handles);

catch ME
    error_show(ME)
end
end

function checkbox4_Callback(hObj, eventdata)
try
    
    handles = guidata(findobj('Tag','GUI'));
    taskinfo = handles.myData.tasks_out{handles.myData.iter};
    if (get(hObj,'Value') == get(hObj,'Max'))
        taskinfo.checkboxresult(4)=1;
    else
        taskinfo.checkboxresult(4)=0;
    end
    set(handles.NextButton,'Enable','on');
    % Pack the results
    handles.myData.tasks_out{handles.myData.iter} = taskinfo;
    guidata(handles.GUI, handles);

catch ME
    error_show(ME)
end
end
%% old
% function radiobutton_Callback(hObj, eventdata)
% try
%     
%     handles = guidata(findobj('Tag','GUI'));
%     taskinfo = handles.myData.tasks_out{handles.myData.iter};
% 
%     taskinfo.button_desc = get(eventdata.NewValue, 'Tag');
%     switch taskinfo.button_desc
%         case 'radiobutton1'
%             taskinfo.buttonID = 1;
%         case 'radiobutton2'
%             taskinfo.buttonID = 2;
%         case 'radiobutton3'
%             taskinfo.buttonID = 3;
%         case 'radiobutton4'
%             taskinfo.buttonID = 4;
%     end
% 
%     % Enable next button
%     set(handles.NextButton,'Enable','on');
% 
%     % Pack the results
%     handles.myData.tasks_out{handles.myData.iter} = taskinfo;
%     guidata(handles.GUI, handles);
% 
% catch ME
%     error_show(ME)
% end
% 
% end
% 
% %% GUI callbacks tasks
% 
% function checkbox1_Callback(hObj, eventdata, handles) %#ok<*INUSL,DEFNU>
% %--------------------------------------------------------------------------
% % This function is executed when the user changes the value of a
% % checkbox. All this function does is calling Update_Next_Button.
% %--------------------------------------------------------------------------
% Update_Next_Button(handles)
% guidata(hObj, handles);
% end
% function checkbox2_Callback(hObj, eventdata, handles) %#ok<DEFNU>
% %--------------------------------------------------------------------------
% % This function is executed when the user changes the value of a
% % checkbox. All this function does is calling Update_Next_Button.
% %--------------------------------------------------------------------------
% Update_Next_Button(handles);
% guidata(hObj, handles);
% end
% function checkbox3_Callback(hObj, eventdata, handles) %#ok<DEFNU>
% %--------------------------------------------------------------------------
% % This function is executed when the user changes the value of a
% % checkbox. All this function does is calling Update_Next_Button.
% %--------------------------------------------------------------------------
% Update_Next_Button(handles);
% guidata(hObj, handles);
% end
% function checkbox4_Callback(hObj, eventdata, handles) %#ok<DEFNU>
% %--------------------------------------------------------------------------
% % This function is executed when the user changes the value of a
% % checkbox. All this function does is calling Update_Next_Button.
% %--------------------------------------------------------------------------
% Update_Next_Button(handles);
% guidata(hObj, handles);
% end

