
% stage_get_pos_thorlabs_script opens a connection to a thorlabs stage.
%   This script is meant to be run in the base environment.

stagePosition = int64([
    savedStage.xChannel.GetPositionCounter, ...
    savedStage.yChannel.GetPositionCounter ...
    ]);

disp("Current position is" + ...
    " x=" + ...
    num2str(stagePosition(1)) + ...
    " y=" + ...
    num2str(stagePosition(2)))
